### ISSUE TITLE
Unexpected error event - spawn ENOENT

### ISSUE THREAD

**Issue by alessioalex** [airportyh/testem#432]
After successfully running the tests in Firefox the processes crashes on Windows 7:

```bash
ok 2 Firefox 27.0 - null
ok 3 Firefox 27.0 - should be equal
ok 4 Firefox 27.0 - should be equivalent
ok 5 Firefox 27.0 - should be equal

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by johanneswuerbach** [comment]
Is your test suite passing otherwise? Could you provide a repo to reproduce this issue?
