### ISSUE TITLE
npm tar pack missing files in node_modules/express

### ISSUE THREAD

**Issue by krisselden** [airportyh/testem#451]
The https://registry.npmjs.org/testem/-/testem-0.6.25.tgz is missing files in node_modules/express and fails with the following when you run testem:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kris/src/yapp/projects/yapp-jslib/node_modules/testem/lib/server/index.js:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by stefanpenner** [comment]
https://github.com/airportyh/testem/blob/master/package.json#L31 seems to indicate this is correct.

**Comment by stefanpenner** [comment]
ah it appears express may have been bundled by mistake.

**Comment by krisselden** [comment]
To clarify extract the tar bundle, `node_modules/express` exists but is missing files so it doesn't work.

**Comment by stefanpenner** [comment]
ah it is bundled https://github.com/airportyh/testem/blob/master/package.json#L73-L75 but as you say it may be corrupted.

**Comment by stefanpenner** [comment]
I can't reproduce:

```sh
wget  https://registry.npmjs.org/testem/-/testem-0.6.25.tgz
tar -zxvf  testem-0.6.25.tgz
cd package
npm i
./testem.js
```

**Comment by stefanpenner** [comment]
able to reproduce with: (thanks @krisselden)

```
mkdir example; cd example; npm init; npm install http://registry.npmjs.org/testem/-/testem-0.6.25.tgz
```

**Comment by stefanpenner** [comment]
diff between my original attempt and the next

```diff
2,3d1
< express/History.md
< express/index.js
5,6d2
< express/lib/application.js
< express/lib/express.js
10,11d5
< express/lib/request.js
< express/lib/response.js
13d6
< express/lib/router/index.js
15,18d7
< express/lib/router/route.js
< express/lib/utils.js
< express/lib/view.js
< express/LICENSE
58,59d46
< express/node_modules/cookie/.npmignore
< express/node_modules/cookie/index.js
61,69d47
< express/node_modules/cookie/package.json
< express/node_modules/cookie/README.md
< express/node_modules/cookie-signature
< express/node_modules/cookie-signature/.npmignore
< express/node_modules/cookie-signature/History.md
< express/node_modules/cookie-signature/index.js
< express/node_modules/cookie-signature/Makefile
< express/node_modules/cookie-signature/package.json
< express/node_modules/cookie-signature/Readme.md
72d49
< express/node_modules/debug/.npmignore
75,77d51
< express/node_modules/debug/component.json
< express/node_modules/debug/debug.js
< express/node_modules/debug/History.md
86,87d59
< express/node_modules/debug/package.json
< express/node_modules/debug/Readme.md
139d110
< express/node_modules/fresh/index.js
141,142d111
< express/node_modules/fresh/package.json
< express/node_modules/fresh/README.md
157d125
< express/node_modules/methods/index.js
159d126
< express/node_modules/methods/package.json
235,236d201
< express/node_modules/range-parser/HISTORY.md
< express/node_modules/range-parser/index.js
238,239d202
< express/node_modules/range-parser/package.json
< express/node_modules/range-parser/README.md
241,242d203
< express/node_modules/send/History.md
< express/node_modules/send/index.js
249,257d209
< express/node_modules/send/node_modules/mime
< express/node_modules/send/node_modules/mime/LICENSE
< express/node_modules/send/node_modules/mime/mime.js
< express/node_modules/send/node_modules/mime/package.json
< express/node_modules/send/node_modules/mime/README.md
< express/node_modules/send/node_modules/mime/test.js
< express/node_modules/send/node_modules/mime/types
< express/node_modules/send/node_modules/mime/types/mime.types
< express/node_modules/send/node_modules/mime/types/node.types
275,276d226
< express/node_modules/send/package.json
< express/node_modules/send/Readme.md
317,318d266
< express/package.json
< express/Readme.md
```

**Comment by airportyh** [comment]
Removed the `bundleDependencies` definition from package.json. https://github.com/airportyh/testem/commit/4f70a22d26b1efc6fef48e35b2d7ad00c8bd36fc

This should fix it. Confirm?

**Comment by stefanpenner** [comment]
@airportyh I suspect that will work, as the bundled express seemed to be incorrect
