### ISSUE TITLE
Undefined is not a function when setting up an API proxy

### ISSUE THREAD

**Issue by adamlc** [airportyh/testem#481]
Hi guys, I'm compltely new to testem and front end testing in general!

I'm trying to setup an API proxy to talk to my backend, but unfortunately testem fails to start with the following error:

```
/usr/local/lib/node_modules/testem/lib/server/index.js:128
        self.proxy = new httpProxy.RoutingProxy({changeOrigin: true})
                     ^
TypeError: undefined is not a function
    at EventEmitter.Server.configureProxy (/usr/local/lib/node_modules/testem/lib/server/index.js:128:22)
    at EventEmitter.Server.createExpress (/usr/local/lib/node_modules/testem/lib/server/index.js:68:10)
    at EventEmitter.Server.start (/usr/local/lib/node_modules/testem/lib/server/index.js:38:10)
    at EventEmitter.App.startServer (/usr/local/lib/node_modules/testem/lib/ci/index.js:58:17)
    at /usr/local/lib/node_modules/testem/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/testem/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/testem/node_modules/async/lib/async.js:149:13)
    at async.eachSeries (/usr/local/lib/node_modules/testem/node_modules/async/lib/async.js:165:9)
    at _asyncMap (/usr/local/lib/node_modules/testem/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/usr/local/lib/node_modules/testem/node_modules/async/lib/async.js:231:23)
```

I'm using testem on a Mac with Yosemite. For reference heres me testem.json, the tests work when I remove the proxy.

```json
{
    "framework": "qunit",
    "src_files": [
      "public/j/libs.js",
      "public/j/app.js",
      "ember/tests/test.js"
    ],
    "launch_in_dev": ["PhantomJS"],
    "launch_in_ci": ["PhantomJS"],
    "proxies": {
        "/api": {
            "port": 80,
            "host": "192.168.59.103"
        }
    }
}
```

Thanks in advance!

**Comment by johanneswuerbach** [comment]
Hello, which node and testem version are you using? I tried your config with 0.6.37 and it looks correct.

**Comment by adamlc** [comment]
Hi @johanneswuerbach , thanks for getting back to be quickly :)

```bash
Adams-MBP:jumplead_beta mooloop$ node -v
v0.10.32
Adams-MBP:jumplead_beta mooloop$ testem -V
0.6.37
```

I'm going to try upgrading node and see if thats helps

**Comment by johanneswuerbach** [comment]
Sorry, I found the issue and will publish a fix soon.

**Comment by adamlc** [comment]
Fantastic, thanks :dancers:
